### ISSUE TITLE
How to use with PATCH method? (or other methods)

### ISSUE THREAD

**Issue by marcelogarbin** [proengsoft/laravel-jsvalidation#255] opened 2017-07-07 13:53 UTC
Usually without the laravel-jsvalidation package I would use the rules as follows:

```
public function rules()
{
  switch($this->method()){
            CASE 'GET':
            CASE 'DELETE':
            {
                return [];
            }
            CASE 'POST':
            {
                return [
                    'field'  => 'required|alpha_num|unique:table,field'
                ];
            }
            CASE 'PUT':
            CASE 'PATCH':
            {
                return [
                    'field'  => 'required|alpha_num|unique:table,field,'.$this->field
                ];
            }
            default: break;
  }
}
```

How can I make these rules with laravel-jsvalidation?

**Comment by a-komarev** [comment] 2017-07-09 18:39
Hello, @marcelogarbin!

I'm not sure that it's possible right out of the box. Because rules for javascript validations generates before user request is being done.

**Comment by marcelogarbin** [comment] 2017-07-09 19:02
@a-komarev Ok, but how can I use the "unique" method with laravel-jsvalidation when updating a record?

**Comment by a-komarev** [comment] 2017-07-09 22:01
@marcelogarbin accordingly unique validator I could only say that I saw a lot of related issues: #138 #142 #176 #162 #164

**Comment by marcelogarbin** [comment] 2017-07-10 01:40
Ok, in that case I can't use unique in Request?

I don't know how to use another alternative in this. Would you have some code example how to do this validation? Or should I stop using the package for this type of registration when prompted for unique.

**Comment by a-komarev** [comment] 2017-07-10 08:57
@marcelogarbin Sorry, I cannot give you exact answer yet. I haven't researched this package completely. But as I can see in Issues above - main developer of this package started to implement this feature in `dev-master` branch and asked people to test it. I'd recommend to read all these issues by yourself.

**Comment by a-komarev** [comment] 2017-07-11 23:39
Closing it since [solution was found](https://github.com/proengsoft/laravel-jsvalidation/issues/164#issuecomment-314355677) and confirmed as working.

**Closed by a-komarev** 2017-07-11 23:39 UTC
Labels: question
