### ISSUE TITLE
A Unique Rule To Ignore A Given ID

### ISSUE THREAD

**Issue by andriy-sa** [proengsoft/laravel-jsvalidation#176] opened 2016-08-15 12:24 UTC
'email' => 'unique:users,email_address,'.$user->id ---- This rule  not working for me!

**Comment by a-komarev** [comment] 2016-08-15 12:28
@andriy-sa could you provide more detailed info and code snippets?

**Comment by andriy-sa** [comment] 2016-08-15 14:14
public function get_rules($update = false){
        $rules =  [
            'title'  => 'required',
            'weight' => 'required|integer',
            'url'    => 'required|regex:/^[0-9a-z]+$/i|unique:pages'
        ];
        if($update){
            $rules['url'] = 'required|regex:/^[0-9a-z]+$/i|unique:pages,url,'.$update;
        }
        return $rules;
}

$js_validator = JsValidator::make($this->get_rules($page->id));

When I try to update page, JS Validator return error to me that page with this url already exist.
JS Validator doesn't ignore page with id that I provide in rules.

**Comment by torrentalle** [comment] 2017-01-22 17:14
related to #162

**Comment by torrentalle** [comment] 2017-01-22 17:25
Can you test if you have this this issue in revelas `v1.4.3`?

**Comment by marcelogarbin** [comment] 2017-07-11 01:00
@andriy-sa Hi, have you been able to use unique for validation?

**Comment by a-komarev** [comment] 2017-07-11 23:39
Closing it since [solution was found](https://github.com/proengsoft/laravel-jsvalidation/issues/164#issuecomment-314355677) and confirmed as working.

**Closed by a-komarev** 2017-07-11 23:39 UTC
Labels: duplicate
