### ISSUE TITLE
Does not support multidimensional array validation

### ISSUE THREAD

**Issue by harishpatel143** [proengsoft/laravel-jsvalidation#365] opened 2019-01-10 16:17 UTC
This package does not support the array validation.

```php
  public function rules()
    {
        return [
            'vehicle_type.*.price' => 'required',
            'vehicle_type.*.distance' => 'required',
        ];
    }
```

Anyone face the same issue?

**Comment by compucoder** [comment] 2019-03-04 12:53
I do and it is a bit of a show stopper to fully use the package. I have had to use server side validation and parse the returned messages and then feed those into Jquery Validate myself, This is definitely something that needs a fixing. Might be able to use their custom validator support to trigger the ajax requests in to better integrate this additional support into the workings of the package. Other than this issue this is an amazing package so very grateful the author made it.

**Comment by compucoder** [comment] 2019-03-14 13:56
Wonder if anyone is able to tackle this; i run into this constantly and don't have the JS chops to solve this myself. Once you do data.*.field_name in your validator you never get local validation rules and nor does it try and send server side either to validate there. Any code ninja's out there able to jump in and make this work?

**Comment by Nuranto** [comment] 2019-04-07 13:21
I do too.

**Comment by OppPMatos** [comment] 2019-09-05 11:54
The problem seems to be a bit hard to solve.
Since the rules are built **before** the java-script is rendered.
They can't be dynamically regenerated, after injected.

**Comment by marcelogarbin** [comment] 2020-01-23 21:55
hi, any news?

**Comment by bytestream** [comment] 2020-03-13 20:34
Duplicate of #297

**Closed by bytestream** 2020-03-13 20:34 UTC
