### ISSUE TITLE
How can i change the default validation message ?

### ISSUE THREAD

**Issue by AmirAmin** [proengsoft/laravel-jsvalidation#27] opened 2015-06-19 13:51 UTC
Hello,

First of all, You have done a great job.

Right now i am validating a filed with name/id "desc", but i don't want to the message like this "The desc field is required." .
So, How can i change the default validation message ? either to be "The description field is required." or at least "This field is required." ?

Note: The validation.required expecting passing a variable :attribute so when i try to remove this variable the code crashes.

Regards,
Amir

**Comment by torrentalle** [comment] 2015-08-09 22:59
Try it in `master` branch

**Comment by torrentalle** [comment] 2015-08-11 20:16
I can't reproduce this issue. Can you post the rules and translations that are you using?

**Comment by torrentalle** [comment] 2015-09-06 16:43
Try with the latest release if your issue is solved

**Comment by cerw** [comment] 2015-09-07 03:34
Hello

I am having same issue, some of the field have "validation.required" under and not sure how to change that?
I am using latest version.

**Comment by torrentalle** [comment] 2015-09-09 20:47
fixed in `dev-master`

**Closed** 2015-09-10 12:12 UTC
Labels: bug
