### ISSUE TITLE
form not submitted with unique rule

### ISSUE THREAD

**Issue by meltzow** [proengsoft/laravel-jsvalidation#267] opened 2017-07-10 12:40 UTC
we use a unique validator (also validation with ajax) in laravel 5.4 but the form can't submited after the validation is done successfully. If I disable this rules its working. we use validation with FormRequest.

any ideas?

**Comment by a-komarev** [comment] 2017-07-10 14:41
This issue seems to be the more required by community: #138 #142 #176 #162 #164

**Comment by a-komarev** [comment] 2017-07-10 14:42
@torrentalle wrote that it's implemented in `dev-master`, but I'm not sure about it. Hope he can answer on this question.

**Comment by akkhan20** [comment] 2017-07-10 18:22
try 'exists' rule if it works or not

**Comment by meltzow** [comment] 2017-07-10 18:57
hi, I am at dev-master. exists rule doesn't work here.

**Comment by akkhan20** [comment] 2017-07-10 19:35
can u confirm if the JS is being generated for the rule?

**Comment by a-komarev** [comment] 2017-07-10 19:50
@meltzow thanks for the test.

**Comment by a-komarev** [comment] 2017-07-11 08:05
@meltzow here @danilodelacruz posted (solution for unique rule usage)[https://github.com/proengsoft/laravel-jsvalidation/issues/164#issuecomment-314355677]

**Comment by a-komarev** [comment] 2017-07-11 23:37
Closing it since solution was found and confirmed as working.

**Closed by a-komarev** 2017-07-11 23:37 UTC
