### ISSUE TITLE
Checkbox name conflict with Jquery Repeater

### ISSUE THREAD

**Issue by OppPMatos** [proengsoft/laravel-jsvalidation#397] opened 2019-09-13 09:30 UTC
Hi.

I use Jquery Repeater to duplicate a few fields, but the rule generated by JSValidation doesn't seem to work with it.

The field in question is the following:
`<input name="ep_is_default" type="checkbox">`

After it being duplicated it now looks like this (First one):
`<input name="group-prof_entities[0][ep_is_default][]" type="checkbox">`

The rule generated doesn't match any element.
`group-prof_entities[*][ep_is_default]`

The difference is that "[]" in the element name.

Any ideas on how to fix this?

I've tried to manually delete the "[]" in the generated name, and the rule apparently worked fine.

**Comment by marcelogarbin** [comment] 2020-01-23 16:55
@OppPMatos did you get any solution?

**Comment by bytestream** [comment] 2020-03-13 20:29
This is an issue with array validation. Duplicate of either #333 or #297

**Closed by bytestream** 2020-03-13 20:29 UTC
