### ISSUE TITLE
Forcing A Unique Rule To Ignore A Given ID

### ISSUE THREAD

**Issue by leoneljdias** [proengsoft/laravel-jsvalidation#162] opened 2016-06-03 09:15 UTC
In release v1.3.1 this problem to "**Forcing A Unique Rule To Ignore A Given ID**" just occurred to me.
I can't use this rule: _'email' => 'unique:users,email_address,'.$user->id_

AJAX calls unique validation only send parameters:

_name:email_address
_jsvalidation:email_address_

where is id? how to use this rule?

**Comment by andriy-sa** [comment] 2016-08-15 12:07
'email' => 'unique:users,email_address,'.$user->id  ---- This rule also not working for me!

**Comment by jdsantos** [comment] 2016-09-09 15:49
Same here. I **SOLVED** my problem using a different approach:
In my **UsersController**, i created a _private function updateValidationRules($id)_:

`private function updateValidationRules($id) {
        $validationRules = ['_userId' => 'required|numeric', 'email' => 'required|email|unique:users,email,'.$id, /* rest of your UPDATE validation logic*/]; 
        return $validationRules;
    }`

In my **_store_** method: 
```
public function store(Request $request) {
        $validationRules = null;
        if($request->has('_userId')){ /**IMPORTANT: _userId must be passed on as a hidden value**/
            $validationRules = $this->updateValidationRules($request->_userId); 
        }else{
            $validationRules = $this->validationRulesCreate;
        }
        /**Rest of your normal store logic**/
}
```

And finally in my _create_user.blade.php_ view template:

`<input type="hidden" name="_userId" value="{{$user->id}}"/>`


The **_store_** method is always called, even for the validation of editions. This means that you must check if a **_userId** parameter exists, in order to run the EDITION validations.

Hope this workaround helps

**Comment by torrentalle** [comment] 2017-01-22 17:25
Can you test if you have this this issue in revelas `v1.4.3`?

**Comment by marcelogarbin** [comment] 2017-07-11 01:01
@jdsantos Hi, have you been able to use unique for validation?

**Comment by a-komarev** [comment] 2017-07-11 23:39
Closing it since [solution was found](https://github.com/proengsoft/laravel-jsvalidation/issues/164#issuecomment-314355677) and confirmed as working.

**Closed by a-komarev** 2017-07-11 23:39 UTC
