### ISSUE TITLE
Library don't working as expected with email validation

### ISSUE THREAD

**Issue by LocalHeroPro** [proengsoft/laravel-jsvalidation#481] opened 2020-08-01 17:29 UTC
### Subject of the issue
Library don't work with email validation.

### Your environment
* version of this package: 4.1.0
* version of Laravel: 7.22.4

### Steps to reproduce
1. Create validation:
```php
public function rules(): array
{
    return = [
        'email' => 'required|string|max:255|email:rfc,dns'
    ];
}
```
2. Enter in input: `example@example` (without Top-Level Domain - TLD)
And JS validation pass that input, fortunately Laravel not!

### Expected behaviour
Proper working JS validatior with `email:dns` valiadtion.

### Actual behaviour
JS validator pass incorrect data.

**Comment by bytestream** [comment] 2020-08-01 19:34
Thanks for the full report, very helpful. 

This is a duplicate of https://github.com/proengsoft/laravel-jsvalidation/issues/476

**Closed by bytestream** 2020-08-01 19:34 UTC
