### ISSUE TITLE
Undefined index: _jsvalidation_validate_all

### ISSUE THREAD

**Issue by pulselife** [proengsoft/laravel-jsvalidation#201] opened 2016-12-21 22:52 UTC
`Undefined index: _jsvalidation_validate_all`
This error shows in the custom validation rules.
Laravel 5.3.28, laravel-jsvalidation - dev-master

**Comment by a-komarev** [comment] 2016-12-22 00:36
@pulselife try to pull `"proengsoft/laravel-jsvalidation": "dev-master",` via composer.

**Comment by pulselife** [comment] 2016-12-22 09:48
I tried but dev-master doesn't work too.
In here people have similar problems with last version of Laravel https://github.com/proengsoft/laravel-jsvalidation/issues/138

**Comment by a-komarev** [comment] 2016-12-22 15:27
As I remember there there were breaking changes in one of the latest 5.3 version.

**Comment by torrentalle** [comment] 2016-12-30 20:05
this shulod be fixed in latest release

**Comment by DeeJaVu** [comment] 2017-01-12 02:32
@torrentalle i get the same error using the latest version 1.4.3 with laravel 5.3.29

**Comment by reganjohnson** [comment] 2017-01-17 13:17
I can confirm I am also seeing this error when attempting to check against a `username` database column using the `required|alpha_dash|min:5|max:18|unique:users,username` rule.

laravel-jsvalidation 1.4.3
laravel/framework 5.3.29

**Comment by reganjohnson** [comment] 2017-01-17 13:25
@DeeJaVu as a quick workaround, I edited: `\Proengsoft\JsValidation\Remote\Resolver::validator()`

Change `$validateAll = $data[$attribute.'_validate_all'] === 'true' ? true : false;` to `$validateAll = array_get($data, $attribute.'_validate_all') === 'true' ? true : false;`

**Comment by torrentalle** [comment] 2017-01-18 18:52
Hi,
can you try to update your public javascript files?
```
php artisan vendor:publish --provider="Proengsoft\JsValidation\JsValidationServiceProvider" --tag=public --force
```

**Comment by a-komarev** [comment] 2017-07-12 00:05
Was it fixed? Any confirmations are welcomed!

**Comment by bytestream** [comment] 2020-03-13 19:25
Due to the volume of issues I'm afraid I'm closing this issue due to lack of activity. This avoids fellow collaborators wasting time investigating this issue, and also prevents giving a false impression that it will eventually be addressed.

To the reporter, please reopen if you still encounter this on the latest version providing a minimal test case. You can also contribute directly by submitting a PR. 

Thanks.

**Closed by bytestream** 2020-03-13 19:25 UTC
