### ISSUE TITLE
Laravel rule "required_if" not working

### ISSUE THREAD

**Issue by adriandmitroca** [proengsoft/laravel-jsvalidation#16] opened 2015-05-15 23:08 UTC
JS is rendered with these rules but validation doesn't work (actual value isn't applied)

**Comment by torrentalle** [comment] 2015-05-17 23:37
Can you post the rules that yo are trying to validate?

**Comment by adriandmitroca** [comment] 2015-05-18 07:43
Sure thing. Example two rules:
`            'distributor_city_id' => 'required_if:type,distributor',`
`            'distributor_name_id' => 'required_if:type,distributor',`

It means that these two fields should be required only when input named `type` has `distributor` value. Unfortunately these fields are required always, no matter what `type` input value is.

**Comment by torrentalle** [comment] 2015-05-18 19:10
I cannot reproduce this error. Can you post the rules and the output generated ?

Thank's

**Comment by torrentalle** [comment] 2015-05-18 19:57
maybe your problem is related to issue #17

**Comment by torrentalle** [comment] 2015-08-09 22:57
This bug is fixed in `master` branch

**Closed by torrentalle** 2015-08-09 22:57 UTC
